apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: fusioniq
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://dev.db.fusioniq.com:3306/dev?createDatabaseIfNotExist=true
  CORS_ALLOWED_ORIGINS: http://royalreddy.site
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fusioniq 
  labels:
    name: backend
    project: fusioniq
    tier: app 
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: backend
      project: fusioniq
      tier: app
  template: 
    metadata:
      labels: 
        name: backend
        project: fusioniq
        tier: app
    spec:
      containers:
      - name: backend
        image: "iamroyalreddy/fusion-backend:0.0.3"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        env:
        - name: SPRING_DATASOURCE_URL # Fixed Name
          valueFrom:
            configMapKeyRef:
              name: backend
              key: SPRING_DATASOURCE_URL
        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: backend
              key: CORS_ALLOWED_ORIGINS
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend
              key: SPRING_DATASOURCE_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: fusioniq
type: Opaque
data: 
  SPRING_DATASOURCE_PASSWORD: aVpSelV5PnVZUXJ3XTNJKHdJd0VmXW18NyNKYw==  # Base64 for password
  SPRING_DATASOURCE_USERNAME: YWRtaW4=
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fusioniq
spec:
  selector:
    name: backend
    project: fusioniq
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port